/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(CommonHeader, CommonHeader, AUTO)


PB_BIND(StatusMessage, StatusMessage, AUTO)


PB_BIND(GpsMessage, GpsMessage, 2)


PB_BIND(SensorDataMessage, SensorDataMessage, 2)




